class OrderPriceRequirements < SitePrism::Page

element :meu_carro_e_um_combo 'select#auto_order_flow_pricing_requirements_vehicle_attributes_make'
element :modelo_carro_combo 'select#auto_order_flow_pricing_requirements_vehicle_attributes_model'
element :ano_modelo_combo 'select#auto_order_flow_pricing_requirements_vehicle_attributes_year'
element :versao_combo 'select#auto_order_flow_pricing_requirements_vehicle_attributes_version'
element :e_o_seu_uso_e_combo 'select#auto_order_flow_pricing_requirements_vehicle_attributes_usage'
element :eu_posse_carro 'select#auto_order_flow_pricing_requirements_vehicle_attributes_purchased'
element :e_uso 'select#auto_order_flow_pricing_requirements_vehicle_attributes_collected'
element :meu_carro_dorme_no_cep_text 'select#auto_order_flow_pricing_requirements_vehicle_attributes_address_attributes_zipcode'
element :sou_do_sexo_combo 'select#auto_order_flow_pricing_requirements_insured_person_attributes_gender'
element :nasci_em 'select#auto_order_flow_pricing_requirements_insured_person_attributes_date_of_birth'
element :meu_estado_civil_e_combo 'select#select#auto_order_flow_pricing_requirements_insured_person_attributes_marital_status'
element :principal_condutor_combo 'select#auto_order_flow_pricing_requirements_driver_attributes_same_as_insured_person'
element :cobertura_idade_inferior_25_combo 'select#auto_order_flow_pricing_requirements_driver_attributes_young_driver'
element :sobre_sinistro 'select#auto_order_flow_pricing_requirements_driver_attributes_years_since_last_claim'
element :proximo_passo_button, 'input#button.button--primary'

  def preenche_proposta_pricing_requirements(carro, modelo, ano, versao, )
    self.meu_carro_e_um_combo.set carro
    self.modelo_carro_combo.set modelo
    self.ano_modelo_combo.set ano
    self.versao_combo.set versao
    self.e_o_seu_uso_e_combo 
  end

end
